#pragma once

#undef RGB_MATRIX_KEYPRESSES
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_DISABLE_TIMEOUT 600000
#define RGB_DISABLE_WHEN_USB_SUSPENDED true
#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_GRADIENT_LEFT_RIGHT
#define RGB_MATRIX_STARTUP_HUE 127
#define RGB_MATRIX_STARTUP_SAT 200
#define RGB_MATRIX_STARTUP_VAL 160
#define RGB_MATRIX_STARTUP_SPD 78
